# Generated by Django 5.1.4 on 2024-12-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appointment_cart_categories_myaddress_order_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.DeleteModel(
            name='MyAddress',
        ),
    ]
