# Generated by Django 5.1.4 on 2024-12-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_products_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='user_id',
        ),
    ]
