# Generated by Django 5.1.4 on 2024-12-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_categories_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
