# Generated by Django 5.1.4 on 2024-12-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_products_img1_products_img2_products_img3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appoiment',
        ),
    ]
