# Generated by Django 5.1.4 on 2024-12-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_appoiment_appoinment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
