# Generated by Django 5.1.4 on 2024-12-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_order_cart_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
