# Generated by Django 5.1.4 on 2024-12-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_cart_tax_cart_total_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_payable',
            field=models.FloatField(null=True),
        ),
    ]
